package com.his.constants;


public enum  ErrorCodeEnum {
	SUCCESS_CODE(0),
	SYSTEM_ERROR_CODE(-1),
	SECURITY_CODE_ERROR(1),
	USER_NOT_EXIST(2),
	MISSING_EMPLOYEE_INFO(3),
	USER_ALREADY_REGISTERED(4),
	MISSING_COMPNAY_INFO(5),
	COMPNAY_ALREADY_REGISTERED(6),
	EMPTY_USERNAME_OR_PASSWORD(7),
	INVALID_USERNAME_OR_PASSWORD(8),
	CHECK_NATIONAL_NUMBER(9),
	MISSING_BRANCH_INFO(10),
	BRANCH_NOT_EXIST(11),
	MISSING_EMPLOYEE_JOB_POST_INFO(12),
	MISSING_COMPANY_JOB_POST_INFO(13),
	CREDIT_CARD_NOT_VALID(14),
	IBAN_NOT_VALID(15),
	MISSING_DOCUMENT_INFO(16),
	MISSING_SEARCH_JOBS_INFO(17),
	INVALID_AVATAR_IMAGE_TYPE(18),
	MAX_100_BRANCHES(19),
	COMPANY_INFO_ADD_BUT_ERROR_ON_ADDING_COMMERCIAL_DOCUMENT(20),
	EMAIL_ALREADY_REGISTERED(21),
	MISSING_USER_ID(22),
	MISSING_JOB_ID(23),
	JOB_POST_NOT_EXOST(24),
	TIMING_OVERLAPPED_WITH_OTHER_JOB(25),
	MISSING_COMPANY_OFFER_REQUEST_INFO(26),
	MISSING_EMPLOYEE_APPLY_REQUEST_INFO(27),
	INVALID_EMPLOYEE(28),
	INVALID_DATE(29),
	OFFER_OVERLAPPING_WITH_OTHER_JOB(30),
	TIMING_OVERLAPPED_WITH_OTHER_JOB_WITH_EMPLOYEE(31),
	COMPANY_OFFER_ALREADY_SENT_BEFORE(32),
	EMPLOYEE_REQUEST_ALREADY_SENT_BEFORE(33),
	EMAIL_NOT_VALID(34),
	ERROR_ON_SAVE(35),
	NOT_COMPLETED_REGISTERATION(36),
	INVALID_COMPANY(37),
	MISSING_OFFER_ID(38),
	OFFER_NOT_EXIST(39),
	MISSING_REQUEST_ID(40),
	NO_MORE_VACANCIES(41),
	PASSWORD_FORMAT_NOT_VALID(42),
	MISSING_COMMERCIAL_RECORD_DOCUMENT_INFO(43),
	NATIONAL_NUMBER_ALREADY_REGISTERED(44),
	NO_ACTIVE_JOB(45),
	ALREADY_SIGNED_IN_TODAY(46),
	ALREADY_SIGNED_OUT_TODAY(47),
	NO_SIGN_IN_DETECTED_TODAY(48),
	CODE_NOT_EXIST(49),
	UNABLE_TO_CANCEL_JOB_POST(50),
	INVALID_RANK(51),
	EMPLOYEE_AGE_MUST_18_60(52),;
	private int errorCode;

	public int intValue() {
		return errorCode;
	}
	
	public String stringValue() {
		return String.valueOf(errorCode); 
	}

	private ErrorCodeEnum(int errorCode) {
		this.errorCode =errorCode;
	}
}
